# Generated by Django 3.2.16 on 2023-01-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='brand',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='fuel_type',
            field=models.CharField(choices=[('diesel', 'diesel'), ('petrol', 'petrol'), ('petrol', 'petrol'), ('petrol', 'petrol'), ('cng', 'cng'), ('ev', 'ev')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='name',
            field=models.CharField(default='name', max_length=200),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='price',
            field=models.PositiveIntegerField(default=50000),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='runned_km',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vehicles',
            name='year',
            field=models.DateField(null=True),
        ),
    ]
